kind: Service
apiVersion: v1
metadata:
  name: react-service
  namespace: developer-stag
  labels:
    app: react-service
  annotations:
    kubesphere.io/creator: admin
spec:
  ports:
    - name: http-80
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30706
  selector:
    app: react-frontend
  clusterIP: 10.101.35.175
  clusterIPs:
    - 10.101.35.175
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
